### ISSUE TITLE
Out of gas Err in callback

### ISSUE THREAD

**Issue by prestwich** [near/near-evm#3]
To reproduce:
```
git fetch && git checkout value
cargo test --lib
```

things I've tried:
1. moving account ID to first callback arg (compilation error, expected &Vec<u8>)
2. passing amount as Balance (compilation error)
3. setting gas to 2**63 (no change)

**Comment by maxzaver** [comment]
The amount attached here is too large: https://github.com/nearprotocol/near-evm/blob/a68a14ef058b95c0483f429151bca6d07628815c/src/lib.rs#L169
it should be smaller than the amount of gas that was prepaid but was not used yet. For example I replaced it with `(env::prepaid_gas() - env::used_gas()) / 2` and now I can see an assertion failing here: https://github.com/nearprotocol/near-evm/blob/0261995796febd122e7617145e2ecd330d1f92c5/src/tests/cryptozombies.rs#L53

**Comment by prestwich** [comment]
Okay, out of gas error is resolved, but now callback doesn't run. Pushed this branch: [callback-problem](https://github.com/nearprotocol/near-evm/tree/callback-problem). To reproduce, run `cargo test --lib test_send_and_retrieve -- --nocapture`. The test will fail the balance assertion, and the `println!` in the callback will not have run. Am I invoking the callback incorrectly?

**Comment by maxzaver** [comment]
Unfortunately, Rust unit tests do not support cross contract calls yet. You would have to test it by spinning up a node. Sorry for that.

**Comment by prestwich** [comment]
Got it. Have the RPC testlib changes made it to `master` on `nearcore` yet?

**Comment by maxzaver** [comment]
> Got it. Have the RPC testlib changes made it to `master` on `nearcore` yet?

@kcole16 @vgrichina ^

**Comment by vgrichina** [comment]
@prestwich @nearmax I’m not sure what are “RPC testlib changes” mentioned here

**Comment by prestwich** [comment]
A week or two ago the testlib RPC user was fixed in `staging` on nearcore. The change doesn't seem to have made it to master yet. Just checked.

**Comment by vgrichina** [comment]
> the testlib RPC user

Still cannot understand what does this refer to. 

@nearmax @prestwich

**Comment by bowenwang1996** [comment]
@vgrichina https://github.com/nearprotocol/nearcore/pull/2001

**Comment by ilblackdragon** [comment]
@prestwich we are for now not releasing new nearcore - we have few breaking changes that need to be tested extensively on large cluster machines. Also we overhauling the release process as well.
It's fine to depend on staging for testing at this point.

**Comment by prestwich** [comment]
Status: callbacks do not work in rust unit tests. Implementing some RPC on local-node unittests to test the callback code

**Comment by ilblackdragon** [comment]
Should be fixed now.
